development: &common_settings
  uploader_mask: abcdefghijklmnopqrstuvwxyz
  webhook_url: http://localhost?file=$FILE
  webhook_credentials: [admin, password]
  upload_dir: upload
  accepted_file_types: [zip,mpg,mpeg,mp4,avi,wmv,mkv,mov]
  exception_sender: '"ExceptionNotification" <sender@example.com>'
  exception_receiver: receiver@example.com

test:
  <<: *common_settings

production:
  <<: *common_settings
